### ISSUE TITLE
Problem when setting up environment with User name beginning with $

### ISSUE THREAD

**Issue by mgrady3** [enthought/okonomiyaki#309]
A problem arises from the following sequence when setting up a runtime environment where the user name begins with $:

https://github.com/enthought/okonomiyaki/blob/master/okonomiyaki/runtimes/runtime_info.py#L111

https://github.com/enthought/okonomiyaki/blob/master/okonomiyaki/runtimes/runtime_info.py#L204

https://github.com/enthought/okonomiyaki/blob/master/okonomiyaki/utils/misc.py#L67

A sample traceback is shown here:
```
2018-03-29 14:25:01 ERROR    1156 Future-thread-1 [edm.utils.misc:154] All Installing runtime attempts failed
2018-03-29 14:25:01 ERROR    1156 Future-thread-1 [canopy.user_env.env_installer:207] Error installing runtime
Traceback (most recent call last):
  File "build\bdist.win32\egg\canopy\user_env\env_installer.py", line 205, in do_install
  File "build\bdist.win32\egg\canopy_platform\runtimes_manager.py", line 375, in install_runtime_from_file
  File "build\bdist.win32\egg\canopy_platform\runtimes_manager.py", line 576, in _install_runtime
  File "build\bdist.win32\egg\canopy_platform\runtimes_manager.py", line 715, in _unpack_with_progress
  File "build\bdist.win32\egg\canopy_platform\edm_api.py", line 95, in wrapper
  File "build\bdist.win32\egg\canopy_platform\edm_api.py", line 338, in install_runtime
  File "build\bdist.win32\egg\edm\core\environments_manager.py", line 371, in install
  File "build\bdist.win32\egg\edm\runtimes\runtime_installer.py", line 282, in install
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\runtimes\runtime_info.py", line 32, in factory_from_metadata
    return runtime_info_from_metadata(metadata, prefix, name)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\runtimes\runtime_info.py", line 201, in runtime_info_from_metadata
    return klass._from_metadata(metadata, prefix, name)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\runtimes\runtime_info.py", line 100, in _from_metadata
    return cls(*cls._from_metadata_impl(metadata, prefix, name))
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\runtimes\runtime_info.py", line 157, in _from_metadata_impl
    metadata, prefix, name
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\runtimes\runtime_info.py", line 111, in _from_metadata_impl
    variables = _compute_variables(metadata, prefix, name)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\runtimes\runtime_info.py", line 215, in _compute_variables
    return substitute_variables(variables, variables)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\utils\misc.py", line 89, in substitute_variables
    ret = _resolve(d)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\utils\misc.py", line 86, in _resolve
    ret[k] = substitute_variable(v, local_vars)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\Lib\site-packages\okonomiyaki\utils\misc.py", line 97, in substitute_variable
    return string.Template(v).substitute(local_vars)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\lib\string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-2.1.8.3709.win-x86\lib\string.py", line 166, in convert
    val = mapping[named]
KeyError: u'xxxxxxxx
```
The KeyError is generated when the user name starts with $, for example $xxxxxxxx.

The substitute_variable() function at https://github.com/enthought/okonomiyaki/blob/master/okonomiyaki/utils/misc.py#L96 uses ```string.Template().substitute()``` to perform Shell/Perl style variable substitution. In this case, a user name beginning with $ is treated as an environment variable and an attempt is made to substitute in the value, which then results in a KeyError since the user name is not present as an environment variable.

A simple way to address this would be to use ```string.Template.safe_substitute()```. As shown here: https://gist.github.com/mgrady3/9bf677e4eb84c479095eca477b68f5ae

However, it may be better to instead try and catch KeyErrors and perform some type of check to see where the substitution failed at. Insert some logic to allow paths with directories beginning with '$' to stay, but raise the error if there indeed should have been a substitution but this failed for some other reason.

**Comment by itziakos** [comment]
Thanks @mgrady3, I would never had expected that `$` is a valid character for usernames on Windows.

**Comment by mgrady3** [comment]
FTR: a quick scan of the Canopy/EDM codebase to check for other instances where this could be an issue yielded:

https://github.com/enthought/canopy/blob/master/canopy/app/runtime_info_service.py#L313
https://github.com/enthought/canopy/blob/master/canopy/notebook_browser/preferences.py#L51

However, in both of these cases, string.Template.safe_substitute() is used, so there should be no problem with KeyErrors there.

In the EDM source tree the following files use string.template.substitute():
https://github.com/enthought/edm/blob/master/vendor/nousagi/nousagi/pre_runs.py
https://github.com/enthought/edm/blob/master/vendor/nousagi/nousagi/assertions.py

**Comment by itziakos** [comment]
The `substitute_variables` command claims that variable substitution can be escaped by using two `$$`. So I think that the right solution is to make sure that the correct value is passed to the function. 

I think that the fix to this specific bug is to make sure that escape the `$` if necessary in the prefix variable in https://github.com/enthought/okonomiyaki/blob/master/okonomiyaki/runtimes/runtime_info.py#L204. However, we need to investigate a little bit more. 

I am removing this issue for the 1.0.0. The bug will be resolved in the next bugfix release.
